name: Build and Push to Container Registry

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

env:
  REGISTRY_PATH: 019c87fc-wild-cetus.registry.twcstorage.ru

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build, tag, and push image to Registry
        env:
          REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
          IMAGE_NAME: ${{ github.repository }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY_PATH/$REGISTRY_ID/$IMAGE_NAME:$IMAGE_TAG .
          docker push $REGISTRY_PATH/$REGISTRY_ID/$IMAGE_NAME:$IMAGE_TAG
