name: Build and Push to Container Registry

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

env:
  REGISTRY_PATH: 019c87fc-wild-cetus.registry.twcstorage.ru

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: 019c87fc-wild-cetus.registry.twcstorage.ru
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY_PATH }}/${{ github.repository  }}:${{ github.sha  }}
